namespace Jank.Objects
{
    /// <summary>
    /// Run by <see cref="IJankInjectable"/> generated by the JankInjectableGenerator to perform actions after injection
    /// if complete.
    /// </summary>
    public interface IPostJankInject
    {
        /// <summary>
        /// Run after all dependencies are injected. Useful to do constructor style work with a guarantee that
        /// dependencies have been pulled
        /// </summary>
        void PostInject();
    }
}